import type { CSSInterface } from '../../utils/interfaces';

const styles: CSSInterface = {
  page: {
    width: '100vw',
    height: '100vh',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative' as const,
    pointerEvents: 'auto',
    isolation: 'isolate',
  },
  content: {
    maxWidth: '1400px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 'clamp(1.5rem, 3vw, 2.5rem)',
    padding: 'clamp(2rem, 4vw, 4rem)',
    position: 'relative' as const,
    zIndex: 2,
  },
  heading: {
    display: 'inline-block',
    fontSize: 'clamp(1rem, 2vw, 1.5rem)',
    fontWeight: '900',
    color: '#fff',
  },
  statement: {
    display: 'inline-block',
    fontSize: 'clamp(1.8rem, 3.6vw, 3.6rem)',
    fontWeight: '300',
    color: 'rgba(255, 255, 255, 0.72)',
  },
  highlight: {
    fontWeight: '500',
    textDecoration: 'underline',
    textDecorationThickness: 'clamp(0.125rem, 0.25vw, 0.25rem)',
    color: '#fff',
    cursor: 'pointer',
    position: 'relative' as const,
    zIndex: 2,
  },
  imagesContainer: {
    position: 'absolute' as const,
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    overflow: 'hidden',
    pointerEvents: 'none' as const,
  },
  image: {
    position: 'absolute' as const,
    height: '20vh',
    width: 'auto',
    opacity: 0,
    zIndex: -1,
    transform: 'scale(0.8)',
    objectFit: 'cover' as const,
  },
  modelSection: {
    position: 'relative' as const,
    flex: 1,
    height: '100%',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
  },
  toggleButton: {
    position: 'absolute' as const,
    bottom: '2rem',
    zIndex: 10,
    padding: '0.5rem 1.4rem',
    background: 'rgba(255, 255, 255, 0.08)',
    color: '#fff',
    border: '1px solid rgba(255, 255, 255, 0.22)',
    borderRadius: '2rem',
    cursor: 'pointer',
    backdropFilter: 'blur(8px)',
    fontSize: '0.8rem',
    letterSpacing: '0.1em',
    fontWeight: '500',
    textTransform: 'uppercase' as const,
  },
};

export default styles;
