import type { CSSInterface } from '../../utils/interfaces';

const slideSpacing = '1rem';
const slideSize = '70vw';

const styles: CSSInterface = {
  container: {
    width: '100vw',
    height: '100vh',
    backgroundColor: '#111',
    overflow: 'hidden',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  backgroundLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    zIndex: 0,
    transform: 'scaleX(-1)',
  },
  carouselWrapper: {
    maxWidth: '100%',
    position: 'relative',
    zIndex: 1,
  },
  carouselViewport: {
    overflow: 'hidden',
  },
  slidesTrack: {
    display: 'flex',
    touchAction: 'pan-y pinch-zoom',
    marginLeft: `calc(${slideSpacing} * -1)`,
  },
  slide: {
    flex: `0 0 ${slideSize}`,
    minWidth: 0,
    paddingLeft: slideSpacing,
  },
  imageCard: {
    overflow: 'hidden',
    borderRadius: '1rem',
  },
  image: {
    objectFit: 'cover',
    pointerEvents: 'none',
    userSelect: 'none',
    borderRadius: '1rem',
  },
  video: {
    objectFit: 'cover',
    pointerEvents: 'none',
    userSelect: 'none',
    transform: 'scale(1.1)',
    borderRadius: '1rem',
  },
  videoWrapper: {
    position: 'relative',
    width: '100%',
    height: '100%',
    borderRadius: '1rem',
    overflow: 'hidden',
  },
  vignetteOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: '100%',
    height: '50%',
    pointerEvents: 'none',
    background: 'linear-gradient(to bottom, transparent 0%, rgba(0, 0, 0, 0.9) 100%)',
  },
  contentOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: '100%',
    height: 'fit-content',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    pointerEvents: 'none',
    zIndex: 2,
  },
  navigationButtonPrev: {
    display: 'flex',
    gap: '1rem',
    justifyContent: 'center',
    marginTop: '2rem',
    position: 'absolute',
    left: '0',
    top: '40%',
    height: '75px',
    width: '25px',
    borderRadius: '0',
  },
  navigationButtonNext: {
    display: 'flex',
    gap: '1rem',
    justifyContent: 'center',
    marginTop: '2rem',
    position: 'absolute',
    right: '1rem',
    top: '40%',
    height: '75px',
    width: '25px',
    borderRadius: '0',
  },
  buttonContainer: {
    display: 'flex',
    flexDirection: 'row',
    gap: 'clamp(0.5rem, 2vw, 1rem)',
    marginTop: 'clamp(1rem, 2vw, 1.5rem)',
    pointerEvents: 'auto',
    zIndex: 3,
    flexWrap: 'wrap',
  },
  actionButton: {
    display: 'flex',
    alignItems: 'center',
    gap: 'clamp(0.25rem, 1vw, 0.5rem)',
    padding: 'clamp(0.5rem, 1.5vw, 0.75rem) clamp(1rem, 2.5vw, 1.5rem)',
    borderRadius: '0.5rem',
    fontSize: 'clamp(0.875rem, 2vw, 1rem)',
    fontWeight: '600',
    transition: 'all 0.3s ease',
    cursor: 'pointer',
    border: 'none',
    pointerEvents: 'auto',
  },
  primaryButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    color: '#111',
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
  },
  secondaryButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    color: 'white',
    border: '2px solid rgba(255, 255, 255, 0.3)',
    backdropFilter: 'blur(10px)',
  },
  buttonIcon: {
    fontSize: 'clamp(1rem, 2vw, 1.2rem)',
    display: 'flex',
    alignItems: 'center',
  },
};

export default styles;
