export interface ExpertiseCategory {
  title: string;
  skills: string[];
}

const expertiseData: ExpertiseCategory[] = [
  {
    title: 'Frontend',
    skills: [
      'React',
      'TypeScript',
      'Next.js',
      'TanStack Query',
      'Tailwind CSS',
      'shadcn/ui',
      'Zustand',
      'Playwright',
      'Vite',
      'Framer Motion',
      'GSAP',
      'Vitest',
      'Jest',
    ],
  },
  {
    title: 'Backend',
    skills: [
      'C#',
      'ASP.NET Core',
      'Azure AD / Entra ID',
      'Azure',
      'Microservices',
      'Clean Architecture',
      'Domain-Driven Design',
      'CQRS / MediatR',
      'REST APIs',
      'JWT / OAuth 2.0',
      'PostgreSQL',
      'Entity Framework',
      'Redis',
      'Kubernetes',
      'SignalR',
      'GraphQL',
      'OpenAPI / Swagger',
      'Supabase',
      'gRPC',
      'xUnit',
    ],
  },
  {
    title: 'AI & Automation',
    skills: [
      'RAG Pipelines',
      'LLM Orchestration',
      'Azure OpenAI',
      'AI Agents',
      'Semantic Kernel',
      'Vector Search',
      'Prompt Engineering',
      'OpenAI API',
      'LangChain',
      'MCP',
      'n8n',
      'Ollama',
      'XGBoost',
      'Time Series Models',
    ],
  },
  {
    title: '3D & Graphics',
    skills: [
      'Three.js',
      'React Three Fiber',
      'WebGL',
      'WebGPU',
      'GLSL / Shaders',
      'OpenGL ES',
      'Postprocessing',
      'Rapier Physics',
      'OGL',
    ],
  },
  {
    title: 'Mobile',
    skills: [
      'Kotlin',
      'Jetpack Compose',
      'Android SDK',
      'Flutter',
      'MVVM',
      'Kotlin Coroutines',
      'Dart',
      'Material You',
      'Android',
      'Java',
      'Cross-Platform',
    ],
  },
  {
    title: 'Tools & Practices',
    skills: [
      'Git',
      'Docker',
      'Kubernetes',
      'GitHub Actions',
      'Azure DevOps',
      'CI/CD',
      'Terraform',
      'Agile',
      'TDD',
      'GitHub Copilot',
      'Claude Code',
      'Cursor',
      'Figma',
      'VS Code',
      'Postman',
      'Grafana',
      'k6',
      'Pulumi',
      'Bruno',
      'Visual Studio Enterprise',
      'Android Studio',
      'Conventional Commits',
      'LM Studio',
      'Adobe XD',
      'axe-core',
      'WCAG',
    ],
  },
];

export default expertiseData;
